Lint that DSA is not used - BR
zmap/zlint pull request #577
Opened 2021-03-14 20:43 UTC by christopher-henderson

I admit that this was largely a copy-paste job of #572 (thanks @robplee !) so right there might be an obvious source of mistakes.

@sleevi I believe this got to at least the minimum of what you were referring to in #537 (sunsetting `dh_params_missing` because it simply doesn't apply anymore). Although, it sounded as though that there might be a slew of DSA BR lints that I may have to hunt down and sunset.

This PR resolves #574

2021-03-14 20:47 UTC, christopher-henderson commented
Ugh, I think the `golangci` tool is looking at all touched files and it doesn't like that we're importing the deprecated `crypto/dsa` package....

2021-03-19 16:53 UTC, robplee approved these changes
Looks good to me, although unless I'm missing something you've not added an import to crypto/dsa so could you explain what you meant about that in your previous comment on the PR?

2021-03-21 18:03 UTC, cpu requested changes
Thanks! Looks good to me once the Golang CI config change is rolled back. We can either administratively merge or wait until master is fixed to merge.

2021-03-21 18:21 UTC, christopher-henderson commented on .golangci.yaml
> +    - staticcheck
Yup, I actually wanted to block my own review because of this but apparently you can't do that.

2021-03-28 14:53 UTC, christopher-henderson commented on .golangci.yaml
> +    - staticcheck
Alright, this all straightened out now. It should be the lone lint now.

2021-03-28 15:11 UTC, cpu approved these changes
Thanks!

2021-03-28 17:02 UTC, merged