DO NOT REVIEW underscores in dns permissible if LDH valid after replacement
zmap/zlint pull request #661
Opened 2022-02-06 19:23 UTC by christopher-henderson

2022-02-13 20:41 UTC, sleevi requested changes
With all the other changes folded in, LGTM. A nit below.

2022-02-13 20:41 UTC, sleevi commented on v3/util/fqdn.go
> +		!strings.HasSuffix(label, "-")
```suggestion
		!strings.HasSuffix(label, "-") &&
		!(util.HasReservedLabelPrefix(label) && !util.HasXNLabelPrefix(label))
```

From https://github.com/zmap/zlint/blob/cb17369b4628c684ac68c1fc169ff2a38c00cfdf/v3/lints/cabf_br/lint_dnsname_contains_prohibited_reserved_label.go#L51

2022-04-02 18:26 UTC, christopher-henderson commented
@sleevi gentle re-engagement on this

2023-09-27 23:16 UTC, dadrian approved these changes

2023-09-27 23:16 UTC, merged