Lint for CABF SMIME 7.1.2.3b - cRLDistributionPoints SHALL be present
zmap/zlint pull request #742
Opened 2023-09-30 15:10 UTC by christopher-henderson

Resolves #741. Addresses ` SMIME certificates SHALL have cRLDistributionPoints (7.1.2.3.b)` from #712

2023-09-30 18:21 UTC, zakird approved these changes

2023-10-05 08:30 UTC, robplee approved these changes

2023-10-05 08:31 UTC, robplee commented on v3/lints/cabf_smime_br/lint_subscribers_shall_have_crl_ddistribution_points_test.go
Same "ddistribution" typo here

2023-10-05 08:32 UTC, robplee requested changes
Easy to fix but there's a couple of typos in the filenames of the lint and it's tests.

2023-10-08 15:33 UTC, merged